### ISSUE TITLE
Possible to have specific layer visibility set to off?

### ISSUE THREAD

**Issue by brianh94** [minorua/Qgis2threejs#101]
Hello! I've been searching for a way to do this but have resorted to changing the transparency to 100% for layers I want to hide. This works somewhat but would be slicker if I could simply turn the Visible attribute off for the layer.

Thanks!

**Comment by DigDigDig** [comment]
I've ended up making my own GUI for the plugin output.  You can set buttons to trigger a function that would toggle the layer that you are trying to get at:

`project.getLayerByName("ExampleLayer").setVisible(!project.getLayerByName("ExampleLayer").visible);`

You can also set the layer visibility to true or false instead of to toggle.

**Comment by brianh94** [comment]
@DigDigDig That works for me. Thanks!

**Comment by qmenen** [comment]
I would appreciate a more detailed explanation on how to do it

**Comment by brianh94** [comment]
@qmenen I simply added the line of code provided by @DigDigDig to the .js file with the same name as the export name. Replace both ExampleLayer with the name of your layer. 

You'll need that line after the layer has already been created, so either put it right after it's instantiated or at the end near the base 64 image data.

**Comment by qmenen** [comment]
Thank you very much, Dig, Brian. This solution opens a wide range of possibilities. Particularly for me in the field of labeling
