### ISSUE TITLE
Allow setting of baseline for DEM sides

### ISSUE THREAD

**Issue by kannes** [minorua/Qgis2threejs#168]
When visualising DEM data that includes negative values, e.g. bathymetry, the "Build sides" option leads to weird results. The parts of the mesh that are below 0 get "upwards" sides (from negative to 0), with normals oriented so that they only show their side towards the DEM.

![image](https://user-images.githubusercontent.com/7661092/54822981-ae0ed300-4ca6-11e9-9ef5-5c5aa856ffc5.png)

![image](https://user-images.githubusercontent.com/7661092/54823067-faf2a980-4ca6-11e9-8eb3-2f411512cfd1.png)

![image](https://user-images.githubusercontent.com/7661092/54823031-dac2ea80-4ca6-11e9-8a40-facaf11e39dc.png)

It would be great if one could specify the baseline for the sides. E.g. if I had a DEM with values between 10 and -10, I might want the sides to reach down to -10 or even further for a nice pedestal effect.

**Comment by DigDigDig** [comment]
You need to set the vertical shift under your world settings.  Input 100.  If it still builds sides above your model then input 1000.  Just dial it in until you get the results you want.

![image](https://user-images.githubusercontent.com/17930616/54831366-988eae80-4c90-11e9-89a3-3c93158c2fac.png)

**Comment by DigDigDig** [comment]
As an aside, any special reason that you went with a diverging color ramp for your bathymetry?

I use this occasionally to show change over time from a median point, but otherwise it just obscures your elevation data.

MATLAB has a ramp called Parula that uses a linear increase in brightness.  I make frequent use of it.

https://blogs.mathworks.com/steve/2014/10/13/a-new-colormap-for-matlab-part-1-introduction/

![image](https://user-images.githubusercontent.com/17930616/54833058-ba3d6500-4c93-11e9-93c8-49afe7fae944.png)

Here's another great article on perception and color:

https://github.com/ResearchComputing/USGS_2015_06_23-25/blob/master/25_June/ColorTheory_References/Why%20Should%20Engineers%20and%20Scientists%20Be%20Worried%20About%20Color.pdf

Sorry for the unsolicited advice.  Just thought I'd throw in my two cents!

**Comment by kannes** [comment]
Oh nice, I never noticed that option. I wonder if it keeps the world coordinates intact, but I am sure it will. Thanks!

I am very aware of color perception, you barked up the wrong tree. Thanks though, for fighting the good fight! Used the divergent scale just for illustration purposes here as the 0 *was* an important breakpoint!
