### ISSUE TITLE
Qgis2threejs Exporter not showing any visualization

### ISSUE THREAD

**Issue by dangarciahe** [minorua/Qgis2threejs#334]
Hello :)

I'm having trouble with the real-time visualization of the exporter. When I go to Web -> Qgis2threejs -> Qgis2threejs Exporter, a windows does pop-up, but I don't see anything in the right panel. The "Preview" button is also grayed out. Tried playing around with several options, and even reinstalling the plugin, but had no luck. However, if I export to Web, a HTML file is generated and I can successfully visualize it in my Firefox web browser. 

Tried both using a search-engine and looking into other Issues, but had not luck, at least not for Linux platforms (and I don't get the "Any 3D objects not registered. There is a compatibility issue with QGIS 3D view..." message that a lot of Windows users get, plus I don't have any 3D views open).

I don't know if it is related, but I wasn't able to enable OpenCL acceleration on my PC, that uses an AMD RX 6700XT in Manjaro Linux. Any suggestion as to how can I solve the issue is greatly appreciated

Below is a screenshot of the Exporter and my setup.

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.34.3-Prizren | QGIS code branch | Release 3.34
-- | -- | -- | --
Qt version | 5.15.12
Python version | 3.11.6
Compiled against GDAL/OGR | 3.8.2 | Running against GDAL/OGR | 3.8.4
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.0-CAPI-1.18.0
Compiled against SQLite | 3.45.0 | Running against SQLite | 3.45.1
Compiled against PDAL | 2.6.2 | Running against PDAL | 2.6.3
PostgreSQL client version | 16.1
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Manjaro Linux
  |   |   |  
Active Python plugins
quick_map_services | 0.19.34
Qgis2threejs | 2.7.3
SRTM-Downloader | 3.2.2
processing | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6
grassprovider | 2.12.99

</body></html>

![Qgis2thtreejs](https://github.com/minorua/Qgis2threejs/assets/54967248/4edd2ac1-f941-4863-969a-72a535b5279b)

**Comment by minorua** [comment]
The reason the preview button is grayed out is because the modules required for the preview are missing.
Probably you can see the following message logged in the QGIS log panel:
`Both webkit widgets and web engine widgets modules not found. The preview gets disabled.`

You can install `python3-pyqt5.qtwebengine` package using `apt` command to enable the preview on Ubuntu 23.04, but I don't know what package should be installed on Manjaro Linux.

**Comment by dangarciahe** [comment]
Thanks for the fast asnwer and the help!

I tried that, but I'm still having troubles:

I installed [python-pyqt5-webengine](https://archlinux.org/packages/extra/x86_64/python-pyqt5-webengine/), and the `Both webkit widgets and web engine widgets modules not found. The preview gets disabled` error dissapears, but now I get a Python error when opening QGIS or enabling the plugin: `QtWebEngineWidgets must be imported or Qt.AA_ShareOpenGLContexts must be set before a QCoreApplication instance is created`

I was able to reproduce the error by running `from PyQt5 import QtWebEngineWidgets` on QGIS's Python console; however, I am able to import the library just fine when running that same code on my computer (no QGIS). 

I also tried compiling PyQt5 from the AUR Arch Linux repository as suggested by https://github.com/minorua/Qgis2threejs/issues/248#issuecomment-1387734795, but then QGIS crashes when opening the Qgis2threejs Exporter. Errors shown on crash at console are almost identical to those of https://github.com/ghtmtt/DataPlotly/issues/343.

The final workaround I tried was installing QGIS with Conda, instead of using Arch official repositories, as suggested in https://github.com/ghtmtt/DataPlotly/issues/343. However, now I get the error `No 3D objects were rendered? There is a compatibility issue with QGIS 3D view. You need to close QGIS 3D view(s) and restart QGIS to use this preview`. I have no 3D views open, and tried with a new profile and a new project, to no success. The "Preview" button is no longer grayed-out, though, and Qgis2threejs log panel doesn't show any error nor warning. Below is the setup of QGIS when using Conda instead.

Do you have any suggestion? 

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.36.1-Maidenhead | QGIS code branch | Release 3.36
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.12.2
GDAL/OGR version | 3.8.4
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.45.2
PDAL version | 2.7.0
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Manjaro Linux
  |   |   |  
Active Python plugins
Qgis2threejs | 2.7.3
SRTM-Downloader | 3.2.2
processing | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6
grassprovider | 2.12.99

</body></html>

**Comment by minorua** [comment]
See https://github.com/minorua/Qgis2threejs/issues/358#issuecomment-2415558196.

Thank you for your feedback.

**Comment by aleczoeller** [comment]
> The reason the preview button is grayed out is because the modules required for the preview are missing. Probably you can see the following message logged in the QGIS log panel: `Both webkit widgets and web engine widgets modules not found. The preview gets disabled.`
> 
> You can install `python3-pyqt5.qtwebengine` package using `apt` command to enable the preview on Ubuntu 23.04, but I don't know what package should be installed on Manjaro Linux.

I had the same issue and this solved it.  In my case (Arch Linux) I had to install python-pyqt5-webengine with pacman, but then everything worked.

**Comment by muttleytm** [comment]
I don't know that this is an issue with the plugin, I am having an issue getting a qgis project into the exporter, probably due to my ignorance.

I'm not doing anything with 3D views. I just have a qgis project that I need to export. I even did this earlier successfully with a different project.

I have the project open. It only consists of three layers. One is georeferenced tiff image and the other two are xyz tile layers. 

I have the project open in qgis and then open the qgis2threejs exporter but nothing is showing up in the preview window and the panel on the left side doesn't list any of the layers. I then tried going to File/export settings and selecting the project. Nothing shows up even after an hour or more.

However, earlier today I was able to do this with a different qgis project that was larger. At first I didn't notice anything in the preview window, but later I could see the layers listed in the panel and I thought later saw the project in the preview window, but maybe was just looking at the open project in qgis below the exporter window.

I've read the tutorial, etc and don't see any steps I've missed. I did see in some comments about 3D projections that there are some external services that are used that may be down. I don't see any error messages or missing libraries, etc.

It did work earlier today but now it isn't working. Earlier was the first time I have ever used it and don't really remember what I did. I just remember it took some time before I saw anything in the preview window.
