### ISSUE TITLE
Age old problem

### ISSUE THREAD

**Issue by matself** [minorua/Qgis2threejs#358]
"No 3D objects were rendered? There is a compatibility issue with QGIS 3D view. You need to close QGIS 3D view(s) and restart QGIS to use this preview."

This is as old as the plugin itself. Anyway, it seem to be persistent now no matter how many times you close and reopen QGIS.
Or does one QGIS 3d viewing for ever infect my instance?
This is on QGIS 3.38.2-Grenoble and plugin version 2.7.3

It is some years since I last used QGIS2Threejs but then it was very useful.

**Comment by minorua** [comment]
I saw the warning message today in QGIS 3.38 on Ubuntu 24.04, and I noticed that the message is inappropriate because it apprears even without having a QGIS 3D view open. The preview of the plugin works fine with  the web engine view. In the next release version, using the web engine view will be given priority over using webkit view.
