### ISSUE TITLE
custom plane heightrange problem

### ISSUE THREAD

**Issue by jodeutmann** [minorua/Qgis2threejs#53]
Dear Akagi Minoru,

first of all thank you very much for this very nice and useful QGIS Plugin. From release to release it become better and better. Since one of the last versions, i don't know exactly which one, the plan height in the plugin is not in the range of the used DEM. For example the DEM have a range between 29.43 m and 102.36 m but the range shown in Qgis2threejs begins with -473m. I hope you can see it in the screenshot shown above. The problem now is, that the plan cannot be positioned very excact with the slider. In my example i try to visualize a flood scenario with a flood range between 30 and 32m and it is very difficult to place the plane with the slider. 

It would be great if you could solve this problem. 

![image](https://cloud.githubusercontent.com/assets/8985259/10687523/fd9ab0b6-796d-11e5-9cfe-b2bdbcf737a5.png)

Thank you very much!
Best regards
Joachim

**Comment by minorua** [comment]
`[zmin - zrange * 0.1, zmax + zrange * 0.1]` might be better than `[zmin - 500, zmax + 1000]`.
https://github.com/minorua/Qgis2threejs/blob/master/js/dat-gui_panel.js#L93

**Comment by jodeutmann** [comment]
Dear Akagi Minoru,

yes, I think that would be a good solution. Do you change it in the next release of Qgis2threejs? In addition, it would be nice if there was a parameter, with which you could specify the increment of the slider. For example, in a flat terrain in decimetres instead of meters.

Thank you very much!
Best regards
Joachim

**Comment by minorua** [comment]
> Do you change it in the next release of Qgis2threejs?

Yes. I will change it.

> In addition, it would be nice if there was a parameter, with which you could specify the increment of the slider. For example, in a flat terrain in decimetres instead of meters.

It would be preferable to create a new template that has menu bar, layer panel and properties dialogs (like [WebGISLab](https://github.com/minorua/WebGISLab) app).

**Comment by koric2** [comment]
@jodeutmann

if you need those changes fast, you could do a dirty hack, like I did:

you have to open the created "dat-gui_panel.js" and jump to the line:

`// Plane height`
`folder.add(parameters.cp, 'd').min(zMin).max(zMax)......`

here you can simply insert your own values for zMin and zMax (which would be 30 for zMin and 32 for zMax in your case)

for setting the increment you can add `step(value)`. to get centimeters you would set the value to 0.01.

the last part is updating the displayed numbers to float, this is done by adding `listen()` and changing the value `d` to a float value like `0.01`. this is a workaround because of a [bug in dat.gui](https://github.com/dataarts/dat.gui/issues/48)

so your dirty hacked line should look like the following:

`d: 0.01,` (can be found at the top of the file)
`folder.add(parameters.cp, 'd').min(30).max(32).step(0.01).listen()......`

this will allow you to set the height of the plane from 30 to 32m by 0.01 (=centimeters) increments and get the correct value displayed

I made a backup, so I can copy the line whenever I create new models with qgis3three.js

I hope this helps you and isn't considered spam, because this is my first post lol

greetz and sorry for my bad english

**Comment by jodeutmann** [comment]
@koric2 

thank you for your help. Yes, i try it an it works! :-) Since it take part in a new release of Qgis2threejs, i will use your simple workaround for my projects.

best regards
Joachim
